apiVersion: v1
kind: Service
metadata:
  name: calculate-service
spec:
  selector:
    app: calculate-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3030
  type: NodePort
